/**
 * Created by Andrewz on 4/21/2017.
 */

exports.ERROR = {
    NO : 0,
    DISPLAY_NAME_INVALID_OR_TAKEN : 1,
    NAME_IS_TAKEN: 2,
    NAME_IS_INVALID: 3,
    NAME_IS_INVALID_OR_TAKEN: 4,
    PASSWORD_IS_INVALID_OR_INCORRECT : 5,
    DISPLAY_NAME_INVALID: 6,
    PASSWORD_IS_INVALID : 7,
    GENERAL_ERROR: 99
};

exports.SUCCESS = 1;
exports.FAILED = 0;
