/**
 * Created by Andrewz on 4/21/2017.
 */

exports.ERROR = {
    NO : 0,
    DISPLAY_NAME_INVALID_OR_TAKEN : 1,
    NAME_IS_TAKEN: 2,
    NAME_IS_INVALID: 3,
    NAME_IS_INVALID_OR_TAKEN: 4,
    PASSWORD_IS_INVALID_OR_INCORRECT : 5,
    DISPLAY_NAME_INVALID: 6,
    PASSWORD_IS_INVALID : 7,
    GENERAL_ERROR: 99
};

exports.HTTP = {
    STATUS_200_OK: 200,
    STATUS_400_BAD_REQUEST: 400,
    STATUS_401_UNAUTHORIZED: 401,
    STATUS_409_CONFLICT: 409,
    STATUS_500_INTERNAL_SERVER_ERROR: 500
};

var AUTH = {
    FACEBOOK: 'facebook',
    TWITTER: 'twitter',
    GOOGLE: 'google'
};

var AUTH_PREFIX = {};
AUTH_PREFIX[AUTH.FACEBOOK] = 'fb';
AUTH_PREFIX[AUTH.TWITTER] = 'tt';
AUTH_PREFIX[AUTH.GOOGLE] = 'gg';

exports.AUTH = AUTH;
exports.AUTH_PREFIX = AUTH_PREFIX;
exports.SUCCESS = 1;
exports.FAILED = 0;
